### ISSUE TITLE
Scrolling doesn't work with upload function

### ISSUE THREAD

**Issue by Tzyinc** [kiangkuang/WhatsLog#1]
when trying to scroll down with uploaded chatlog, instead of continuing the new chatlog, it keeps reloading the default chatlog
![bug](https://cloud.githubusercontent.com/assets/17025450/17050228/5a3405c4-5024-11e6-82f5-9120cbe516b8.jpg)

**Comment by jackyhsuch** [comment]
fixed, load 10 messages at a time. can increase if needed
